spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CoworkingDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=Admin
spring.datasource.password=Admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.current_session_context_class=thread

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000

spring.jpa.packages-to-scan=com.example.coworking_web.model
